services: 
  anki-desktop: 
    container_name: anki-desktop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/apps/anki/config:/config/app
    ports: 
      - 3000:3000
      # Anki Connect port
      - 8765:8765
